[project]
name = "currency-conversion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "mcp>=1.6.0",
    "requests>=2.32.3",
]
